language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get -t -d -v ./... && go build -v ./...

script:
  - go test -v -race ./...